---
- hosts: ubuntu
  vars:
      username: www

  tasks:  
    - name: "Install packages"
      become: true
      apt:
        pkg:
          - vim
          - tmux
          - git
          - curl
          - wget
          - htop
          - bat
          - jq
          - net-tools
          - build-essential
          - python3-pip
          - python3-venv
          - ca-certificates
          - gnupg
        update_cache: yes

    - name: "Allow new user"
      become: true
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^AllowUsers"
        line: "AllowUsers {{ username }}"
        state: present
        backup: yes

    - name: "Disable Root Login"
      become: true
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
        state: present
        backup: yes
      notify:
        - Restart SSH

  handlers:
    - name: Restart SSH
      become: yes
      service:
        name: sshd
        state: restarted
