---
- hosts: ubuntu

  tasks:  
    - name: "Install packages"
      become: true
      apt:
        pkg:
          - vim
          - tmux
          - git
          - curl
          - wget
          - htop
          - bat
          - build-essential
          - python3-pip
          - python3-venv
          - ca-certificates
          - gnupg
        update_cache: yes
